services:
  frontend:
    image: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://127.0.0.1/api/
    command: bash -c "npm run build && serve -s -l 5000 build"
  backend:
    image: backend
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - PORT=8081
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ~/database:/var/lib/postgresql/data
  reverse_proxy:
    image: nginx
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
