services:
  frontend:
    image: frontend
    ports:
      - 127.0.0.1:8080:5000
  backend:
    image: backend
    ports:
      - 127.0.0.1:80:8081
    environment:
      - REQUEST_ORIGIN=http://localhost:8080
      - REDIS_HOST=redis
      - PORT=8081
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
